(defun UF1 (x)
(+ (expt 5 (sin x)) (expt 5 (cos (* × 5
))))
)
(defun UF2 (x)
(* (expt (sin x) x) (+ x (/ pi 4)))
(setq UFR (list (UF1 10) (UF2 10)))
(setq len (length UFR))
(setq rev (reverse UFR))
(setq result (Eval (cons '+ UFR)))
(write result)
(terpri)
(write len)
(terpri)
(write rev)

