name: project_anagement
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  get: ^4.6.5
  get_storage: ^2.0.3
  cherry_toast: 1.0.8
  shared_preferences: ^2.0.15
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^1.1.6
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  rename: ^2.1.1
  flutter_local_notifications: ^9.7.0
  sign_in_with_apple: ^4.3.0
  auth_buttons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
   - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic